=== crkimberley/iwt/dtd_exercises/exam.dtd
<!ELEMENT exam		(code, title, date, questions)>
<!ELEMENT date		(month, year)>
<!ELEMENT questions	(question, question, question, question, question, question?)>
<!ELEMENT question	((part)+)>
<!ELEMENT part		(#PCDATA|part)*>
<!ELEMENT code 		(#PCDATA)>
<!ELEMENT title 	(#PCDATA)>
<!ELEMENT month 	(#PCDATA)>
<!ELEMENT year 		(#PCDATA)>

=== crkimberley/iwt/week03/exam1.xml
<?xml version="1.0"?>
<!DOCTYPE exam SYSTEM "/Users/chris/x/iwt/week04/exam.dtd">
<exam>
    <code>SDP</code>
    <title>Software Design and Programming</title>
    <date>
        <month>June</month>
        <year>2017</year>
    </date>
    <questions>
        <question>
            <part>q1</part>
        </question>
        <question>
            <part>q2</part>
        </question>
        <question>
            <part>q3</part>
        </question>
        <question>
            <part>q4</part>
        </question>
        <question>
            <part>q5</part>
        </question>
    </questions>
</exam>
